;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	comment-or-uncomment-region-or-line
	completion-at-point
	cua-paste
	ignore
	indent-for-tab-command
	markdown-exdent-or-delete
	markdown-outdent-or-delete
	ns-cut
	ns-delete-line
	slime-autodoc-space
	tab-to-tab-stop
	typescript-insert-and-autoconvert-to-template
	typescript-insert-and-indent
	))

(setq mc/cmds-to-run-once
      '(
	beginning-of-buffer
	end-of-buffer
	goto-last-change
	keyboard-escape-quit
	mouse-set-region
	ns-save
	sc-execute-main-utilities
	sc-execute-run-applications
	select-file-menu
	select-modif-request-action
	tabbar-backward
	tabbar-forward
	tabbar-select-tab-callback
	w32-drag-n-drop
	x-sc-mouse-drag-region
	))
